# Generated by Django 3.2.6 on 2022-10-16 06:51

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, help_text='数据uuid', length=22, max_length=64, null=True, prefix='', unique=True)),
                ('tenant', models.CharField(help_text='租户用户名', max_length=32, unique=True)),
                ('name', models.CharField(blank=True, help_text='租户名称', max_length=32, null=True)),
                ('password', models.CharField(help_text='密码', max_length=32)),
                ('status', models.CharField(choices=[('FORBIDDEN', 'FORBIDDEN'), ('NORMAL', 'NORMAL'), ('DELETE', 'DELETE')], default='NORMAL', help_text='账户状态', max_length=64)),
                ('is_superuser', models.BooleanField(default=False, help_text='是否超级管理员')),
                ('last_login', models.DateTimeField(auto_now=True, db_column='last_login', help_text='最后登录')),
            ],
            options={
                'verbose_name': '租户表',
                'db_table': 'tenant',
            },
        ),
    ]
