# Generated by Django 3.2.4 on 2022-10-18 02:11

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='token_version',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, help_text='版本', length=22, max_length=64, prefix=''),
        ),
    ]
